In [415]:

import pandas as pd
import numpy as np

In [416]:
df1=pd.read_csv('/Users/shobhitsharma/Downloads/DataScience/Gdp-updated 2.csv')
df1

,Year,"Agriculture, forestry & fishing",Mining & quarrying,Manufacturing,"Electricity, gas ,water supply & utility",Construction,"Trade, hotels, transport, communication and services related to broadcasting","Financial, real estate & professional services","Public administration, defence and Other Services",GDP
0,2011,323222,64670,350857,44662,182219,330070,395102,225669,2043496
1,2011,270231,55463,329937,46631,189096,337631,407657,263657,2029469
2,2011,505545,65815,334727,47957,197079,351579,343065,245399,2244852
3,2011,402949,75087,394465,47418,208941,393836,385053,291257,2418511
4,2012,360094,75789,374606,54330,203182,394347,461070,263982,2313203
5,2012,302961,59899,395939,52471,202602,403846,479904,304587,2356953
6,2012,557597,70447,377768,54453,211963,412552,400489,271594,2548378
7,2012,454454,79707,424523,54095,231618,453240,435169,323412,2725479
8,2013,407713,70645,413131,62946,221810,427470,533978,303684,2565374
9,2013,350835,63145,424395,65066,224408,456946,585666,341392,2686203
10,2013,670113,74589,416194,64911,231690,480886,459327,308435,2921070
11,2013,497711,87415,459732,67231,243562,509165,490537,348424,3060874
12,2014,460964,95040,471159,69662,247541,508205,620774,334552,2914393
13,2014,404350,68894,476474,71641,246390,517595,695118,390144,3053982
14,2014,688923,72720,435195,70691,242325,514666,520847,394998,3184917
15,2014,539374,71822,495542,70264,242829,567130,526608,371841,3314667
16,2015,499370,90269,530752,83640,253252,553748,690657,371179,3243543
17,2015,424241,61138,534069,87112,237074,541866,773347,433096,3355884
18,2015,721066,68977,506027,81634,248149,558605,577564,442648,3476632
19,2015,582855,73627,575342,82579,252608,640294,584570,413144,3695814
20,2016,573092,81934,575997,88422,273538,607116,783003,417101,3639775
21,2016,485562,60518,575852,89213,262498,594624,874053,484122,3754117
22,2016,801318,76935,554950,88829,274360,619242,619110,503381,3875007
23,2016,658690,107421,626923,89245,270473,718175,635271,494233,4122771
24,2017,614682,89447,583784,106824,287451,672181,867582,492027,4007453
25,2017,544703,69310,633546,107304,280664,661102,944159,544308,4172122
26,2017,903485,86182,620420,103950,305759,694315,696275,573664,4326105
27,2017,734038,112849,708858,107023,324057,785108,698542,559522,4592624
28,2018,655799,98202,664844,113836,324955,758987,974229,565871,4551224
29,2018,560416,80476,692530,118456,314756,744890,1068600,623661,4647831
30,2018,924273,97355,673890,113804,345528,778223,785893,649806,4817413
31,2018,782358,113290,735502,110316,359041,860520,793409,656245,4954770
32,2019,712222,104945,694993,124751,350920,806915,1056866,637682,4918228
33,2019,608227,75826,687906,122547,325815,783108,1138695,723713,4920694
34,2019,1053034,92789,664294,115188,349232,821438,818382,760995,5173234
35,2019,883959,119543,728394,124030,358928,905193,828581,764128,5327693
36,2020,752768,61586,421746,118150,170611,424739,1010899,605507,3808193
37,2020,655053,62218,699930,118709,298505,702556,1072756,670348,4722068

In [417]:
df_2020=df1.iloc[36:,:]
df_new=df1.iloc[:-2,:]
df_new

,Year,"Agriculture, forestry & fishing",Mining & quarrying,Manufacturing,"Electricity, gas ,water supply & utility",Construction,"Trade, hotels, transport, communication and services related to broadcasting","Financial, real estate & professional services","Public administration, defence and Other Services",GDP
0,2011,323222,64670,350857,44662,182219,330070,395102,225669,2043496
1,2011,270231,55463,329937,46631,189096,337631,407657,263657,2029469
2,2011,505545,65815,334727,47957,197079,351579,343065,245399,2244852
3,2011,402949,75087,394465,47418,208941,393836,385053,291257,2418511
4,2012,360094,75789,374606,54330,203182,394347,461070,263982,2313203
5,2012,302961,59899,395939,52471,202602,403846,479904,304587,2356953
6,2012,557597,70447,377768,54453,211963,412552,400489,271594,2548378
7,2012,454454,79707,424523,54095,231618,453240,435169,323412,2725479
8,2013,407713,70645,413131,62946,221810,427470,533978,303684,2565374
9,2013,350835,63145,424395,65066,224408,456946,585666,341392,2686203
10,2013,670113,74589,416194,64911,231690,480886,459327,308435,2921070
11,2013,497711,87415,459732,67231,243562,509165,490537,348424,3060874
12,2014,460964,95040,471159,69662,247541,508205,620774,334552,2914393
13,2014,404350,68894,476474,71641,246390,517595,695118,390144,3053982
14,2014,688923,72720,435195,70691,242325,514666,520847,394998,3184917
15,2014,539374,71822,495542,70264,242829,567130,526608,371841,3314667
16,2015,499370,90269,530752,83640,253252,553748,690657,371179,3243543
17,2015,424241,61138,534069,87112,237074,541866,773347,433096,3355884
18,2015,721066,68977,506027,81634,248149,558605,577564,442648,3476632
19,2015,582855,73627,575342,82579,252608,640294,584570,413144,3695814
20,2016,573092,81934,575997,88422,273538,607116,783003,417101,3639775
21,2016,485562,60518,575852,89213,262498,594624,874053,484122,3754117
22,2016,801318,76935,554950,88829,274360,619242,619110,503381,3875007
23,2016,658690,107421,626923,89245,270473,718175,635271,494233,4122771
24,2017,614682,89447,583784,106824,287451,672181,867582,492027,4007453
25,2017,544703,69310,633546,107304,280664,661102,944159,544308,4172122
26,2017,903485,86182,620420,103950,305759,694315,696275,573664,4326105
27,2017,734038,112849,708858,107023,324057,785108,698542,559522,4592624
28,2018,655799,98202,664844,113836,324955,758987,974229,565871,4551224
29,2018,560416,80476,692530,118456,314756,744890,1068600,623661,4647831
30,2018,924273,97355,673890,113804,345528,778223,785893,649806,4817413
31,2018,782358,113290,735502,110316,359041,860520,793409,656245,4954770
32,2019,712222,104945,694993,124751,350920,806915,1056866,637682,4918228
33,2019,608227,75826,687906,122547,325815,783108,1138695,723713,4920694
34,2019,1053034,92789,664294,115188,349232,821438,818382,760995,5173234
35,2019,883959,119543,728394,124030,358928,905193,828581,764128,5327693

In [431]:
actual_gdp=df_2020.iloc[:, -1]
df_2020

ip=df_2020.iloc[:,0:-1]
ip=ip.iloc[:,1:]
#ip = scaler.fit_transform(ip)

In [432]:

actual_gdp

36    3808193
37    4722068
Name: GDP , dtype: int64

In [420]:
X = df_new.iloc[:, 0:-1]
Y = df_new.iloc[:, -1]
X=X.iloc[:,1:]
X

,"Agriculture, forestry & fishing",Mining & quarrying,Manufacturing,"Electricity, gas ,water supply & utility",Construction,"Trade, hotels, transport, communication and services related to broadcasting","Financial, real estate & professional services","Public administration, defence and Other Services"
0,323222,64670,350857,44662,182219,330070,395102,225669
1,270231,55463,329937,46631,189096,337631,407657,263657
2,505545,65815,334727,47957,197079,351579,343065,245399
3,402949,75087,394465,47418,208941,393836,385053,291257
4,360094,75789,374606,54330,203182,394347,461070,263982
5,302961,59899,395939,52471,202602,403846,479904,304587
6,557597,70447,377768,54453,211963,412552,400489,271594
7,454454,79707,424523,54095,231618,453240,435169,323412
8,407713,70645,413131,62946,221810,427470,533978,303684
9,350835,63145,424395,65066,224408,456946,585666,341392
10,670113,74589,416194,64911,231690,480886,459327,308435
11,497711,87415,459732,67231,243562,509165,490537,348424
12,460964,95040,471159,69662,247541,508205,620774,334552
13,404350,68894,476474,71641,246390,517595,695118,390144
14,688923,72720,435195,70691,242325,514666,520847,394998
15,539374,71822,495542,70264,242829,567130,526608,371841
16,499370,90269,530752,83640,253252,553748,690657,371179
17,424241,61138,534069,87112,237074,541866,773347,433096
18,721066,68977,506027,81634,248149,558605,577564,442648
19,582855,73627,575342,82579,252608,640294,584570,413144
20,573092,81934,575997,88422,273538,607116,783003,417101
21,485562,60518,575852,89213,262498,594624,874053,484122
22,801318,76935,554950,88829,274360,619242,619110,503381
23,658690,107421,626923,89245,270473,718175,635271,494233
24,614682,89447,583784,106824,287451,672181,867582,492027
25,544703,69310,633546,107304,280664,661102,944159,544308
26,903485,86182,620420,103950,305759,694315,696275,573664
27,734038,112849,708858,107023,324057,785108,698542,559522
28,655799,98202,664844,113836,324955,758987,974229,565871
29,560416,80476,692530,118456,314756,744890,1068600,623661
30,924273,97355,673890,113804,345528,778223,785893,649806
31,782358,113290,735502,110316,359041,860520,793409,656245
32,712222,104945,694993,124751,350920,806915,1056866,637682
33,608227,75826,687906,122547,325815,783108,1138695,723713
34,1053034,92789,664294,115188,349232,821438,818382,760995
35,883959,119543,728394,124030,358928,905193,828581,764128

In [421]:
#from sklearn import preprocessing
#Y = preprocessing.normalize([Y])
#x_array = np.array(df1['Total Gross Value Added at Basic Price'])
#Y=pd.DataFrame(Y.T)

In [426]:
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split



model1 = MLPRegressor(hidden_layer_sizes=(8,8,8,8,8,8,8,8), max_iter=5000)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)
#X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [427]:
X_train

,"Agriculture, forestry & fishing",Mining & quarrying,Manufacturing,"Electricity, gas ,water supply & utility",Construction,"Trade, hotels, transport, communication and services related to broadcasting","Financial, real estate & professional services","Public administration, defence and Other Services"
7,454454,79707,424523,54095,231618,453240,435169,323412
6,557597,70447,377768,54453,211963,412552,400489,271594
11,497711,87415,459732,67231,243562,509165,490537,348424
16,499370,90269,530752,83640,253252,553748,690657,371179
10,670113,74589,416194,64911,231690,480886,459327,308435
25,544703,69310,633546,107304,280664,661102,944159,544308
15,539374,71822,495542,70264,242829,567130,526608,371841
33,608227,75826,687906,122547,325815,783108,1138695,723713
20,573092,81934,575997,88422,273538,607116,783003,417101
26,903485,86182,620420,103950,305759,694315,696275,573664
28,655799,98202,664844,113836,324955,758987,974229,565871
17,424241,61138,534069,87112,237074,541866,773347,433096
21,485562,60518,575852,89213,262498,594624,874053,484122
24,614682,89447,583784,106824,287451,672181,867582,492027
13,404350,68894,476474,71641,246390,517595,695118,390144
3,402949,75087,394465,47418,208941,393836,385053,291257
9,350835,63145,424395,65066,224408,456946,585666,341392
19,582855,73627,575342,82579,252608,640294,584570,413144
5,302961,59899,395939,52471,202602,403846,479904,304587
35,883959,119543,728394,124030,358928,905193,828581,764128
29,560416,80476,692530,118456,314756,744890,1068600,623661
34,1053034,92789,664294,115188,349232,821438,818382,760995
18,721066,68977,506027,81634,248149,558605,577564,442648
4,360094,75789,374606,54330,203182,394347,461070,263982
22,801318,76935,554950,88829,274360,619242,619110,503381
12,460964,95040,471159,69662,247541,508205,620774,334552
14,688923,72720,435195,70691,242325,514666,520847,394998

In [428]:

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)




model1.fit(X_train, Y_train)

model1

/Users/shobhitsharma/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPRegressor(hidden_layer_sizes=(8, 8, 8, 8, 8, 8, 8, 8), max_iter=5000)

In [429]:
from sklearn.metrics import mean_squared_error, r2_score
Ya = Y_test
Ya=Ya.to_numpy()
Yp = model1.predict(X_test)

mse = mean_squared_error(Ya, Yp)
R2 = r2_score(Ya, Yp)
'R2-Score : {}'.format(R2)

'R2-Score : 0.9719720814568605'

In [412]:
ip = scaler.transform(ip)
ip

predicted_gdp=model1.predict(ip)

predicted_gdp

array([10805998.61907237, 10805967.28797651])

In [413]:
actual_gdp

36    3808193
37    4722068
Name: GDP , dtype: int64

In [357]:
#df1=pd.read_csv('/Users/shobhitsharma/Downloads/DataScience/gdp_data.csv')
#df2=pd.read_csv('/Users/shobhitsharma/Downloads/DataScience/nifty_data.csv')
#df3=pd.read_csv('/Users/shobhitsharma/Downloads/DataScience/sensex_data.csv')
#df2=df2.drop(['Adj Close'],axis=1)
#df3=df3.drop(['Adj Close'],axis=1)

In [358]:
#df2_new=df2.iloc[:,2:]
#df2_new=df2_new.rename({'Open': 'sensex_open', 'High': 'sensex_High','Low':'sensex_Low','Close': 'sensex_close', 'Volume': 'sensex_Volume'}, axis=1)

In [359]:
#df3_new=df3.iloc[:,2:]
#df3_new=df3_new.rename({'Open': 'nifty_open', 'High': 'nifty_High','Low':'nifty_Low','Close': 'nifty_close', 'Volume': 'nifty_Volume'}, axis=1)

In [360]:
#df3_new

In [363]:
#merge=pd.read_csv('/Users/shobhitsharma/Downloads/DataScience/file.csv')

#x=merge.iloc[:,2:]
#x=merge.iloc[:-2,:]

In [364]:
#merge